apiVersion: v1
kind: Secret
metadata:
  name: -kafka-credentials
stringData:
  bootstrap-servers: "PLACEHOLDER"
  api-key: "PLACEHOLDER"
  api-secret: "PLACEHOLDER"
  schema-registry-url: "PLACEHOLDER"
  schema-registry-api-key: "PLACEHOLDER"
  schema-registry-api-secret: "PLACEHOLDER"
