apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: -default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: PLACEHOLDER_KARPENTER_NODE_ROLE
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: PLACEHOLDER_CLUSTER_NAME
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: PLACEHOLDER_CLUSTER_NAME
