apiVersion: v1
kind: Secret
metadata:
  name: -gitlab-registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"registry.example.com":{"auth":"PLACEHOLDER"}}}'
