apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../workloads/deployment-worker
  - ../../components/serviceaccount

configurations:
  - ../../kustomizeconfig.yaml

namePrefix: sample-worker

labels:
  - pairs:
      app: sample-worker
    includeSelectors: true

images:
  - name: PLACEHOLDER_IMAGE
    newName: registry.example.com/example/sample-worker
    newTag: "1.0.0"
